### ISSUE TITLE
Fatal error: Class 'Expedia' not found in  

### ISSUE THREAD

**Issue by rmak78** [dyatlov/Expedia-PHP-API#1]
I am getting following error when running example.php
I have tried using require and changing paths, but it does not work

Fatal error: Class 'Expedia' not found in C:\Program Files (x86)\EasyPHP-12.1\www\expedia-dev\example.php on line 8

**Comment by dyatlov** [comment]
Yeah, there was a typo in example. You have to use API class instead of Expedia.
I also updated code to include required classes (beforehand it was aimed to have an autoloader registered somewhere);

**Comment by Ajay1432** [comment]
I got this message "Uncaught exception 'Dyatlov\Expedia\Exception' with message 'Authentication failure." As per my knowledge this is due to bad ip address. but i want to use this example by shared key. can I?
